### ISSUE TITLE
vim.exe (and possibly other files) missing from latest builds

### ISSUE THREAD

**Issue by dmarnerides** [conda-forge/vim-feedstock#1616]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The vim.exe file is missing from the archives (and final installation) for win-64 Python 3.8 (possibly other win-64 versions too).
e.g.
This version contains the exe:
https://anaconda.org/conda-forge/vim/8.2.3427/download/win-64/vim-8.2.3427-py38h885f38d_4.tar.bz2

This version (currently latest) does not:
https://anaconda.org/conda-forge/vim/8.2.3901/download/win-64/vim-8.2.3901-py38pl5321h885f38d_0.tar.bz2

### Installed packages

```shell
(not on a windows machine now - sorry)
```

### Environment info

```shell
(not on a windows machine now - sorry)
```

**Comment by cjwomack** [comment]
I also found I had this problem too

`conda list vim
# packages in environment at C:\ProgramData\Miniconda3:
#
# Name                    Version                   Build  Channel
vim                       8.2.3901        py39pl5321h415ef7b_0    conda-forge`

**Comment by matthiasdiener** [comment]
Thank you for the reports! #1624 should fix this, please let me know if there are still issues. I also made the test more strict, so this should hopefully not happen again.
