### ISSUE TITLE
Feature Request: clipboard support enabled

### ISSUE THREAD

**Issue by broander** [conda-forge/vim-feedstock#1648]
Hi, would you please add system clipboard support to the compilation configuration?  It's convenient when working with WSL containers and codespaces using windows terminal to be able to paste text from vim back into windows.

Thanks!

**Comment by matthiasdiener** [comment]
Do you know which option we would need to enable for the configuration? According to https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=598714&view=logs&jobId=171a126d-c574-5c8c-1269-ff3b989e923d&j=171a126d-c574-5c8c-1269-ff3b989e923d&t=1183ba29-a0b5-5324-8463-2a49ace9e213 , vim has the `+clipboard` support enabled.

**Comment by broander** [comment]
Interesting, I have the conda-forge vim package installed, and here's what vim --version looks like:
![image](https://user-images.githubusercontent.com/66220841/227415948-19f30e43-75c8-4cd7-9981-cc92afa8fc04.png)
According to that image, it's the conda-forge version, and clipboard is listed as disabled.

**Comment by broander** [comment]
Okay, just did some testing in a clean debian image, here's the dependencies you need to install as clipboard support relies on x11 behind the scenes: sudo apt install dbus-x11 libx11-dev xserver-xorg-dev xorg-dev

Regarding the configure command, from what I see in the azure devops pipeline logs, you need to remove this argument: --without-x

It should compile enabled with those changes, the underlying feature is enabled by default otherwise (part of the "huge" install being enabled by default in the last several iterations of VIM).  All the other config args can stay the same.

**Comment by matthiasdiener** [comment]
Thanks for tracking this down @broander ! https://github.com/conda-forge/vim-feedstock/pull/1649 should add the clipboard support on Linux.

**Comment by broander** [comment]
I see your pull request has merged.  I just updated the vim package using mamba, and I can verify that clipboard is now enabled for vim.  Thanks!

**Comment by matthiasdiener** [comment]
Thanks for testing this @broander!
